site_name: specification v1.2
repo_url: https://github.com/swhid/specification
edit_uri: blob/main/Chapters/
docs_dir: Chapters
theme: readthedocs
extra_css:
- css/style.css
use_directory_urls: true
nav:

- 'Copyright': index.md
- 'Foreword': 0.Foreword.md
- 'Introduction': 0.Introduction.md
- 'Clause 1: Scope': 1.Scope.md
- 'Clause 2: Normative references': 2.Normative_references.md
- 'Clause 3: Terms and definitions': 3.Terms_and_definitions.md
- 'Clause 4: Syntax': 4.Syntax.md
- 'Clause 5: Core Identifiers': 5.Core_identifiers.md
- 'Clause 6: Qualified Identifiers': 6.Qualified_identifiers.md
- 'Annex A: Conformance': A.Conformance.md
- 'Annex B: Bibliography': B.Bibliography.md
copyright: Copyright &copy; 2022–2025 SWHID Contributors.

markdown_extensions:
- codehilite:
   guess_lang: false
